# These are supported funding model platforms

github: Justmwangii, Maxwell Muthui Mwangi # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: @justmwangii # Replace with a single Patreon username
open_collective: @justmwangii # Replace with a single Open Collective username
ko_fi: @justmwangii # Replace with a single Ko-fi username
tidelift: @justmwangii # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: @justmwangii # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: @justmwangii # Replace with a single Liberapay username
issuehunt: @justmwangii # Replace with a single IssueHunt username
lfx_crowdfunding: @justmwangii # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: @justmwangii # Replace with a single Polar username
buy_me_a_coffee: @justmwangii # Replace with a single Buy Me a Coffee username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
